### DISCUSSION TITLE
自编译了一个 yesplaymusic 的docker镜像，欢迎拉取使用~

### DISCUSSION THREAD

**Discussion by junlongzzz** [qier222/YesPlayMusic#2147] [General]
如题，DockerHub地址为 https://hub.docker.com/r/junlongzzz/yesplaymusic

[![Docker Pulls](https://img.shields.io/docker/pulls/junlongzzz/yesplaymusic)](https://hub.docker.com/r/junlongzzz/yesplaymusic)

---

# YesPlayMusic (Web Version)

## Introduction

镜像内编译的是 [YesPlayMusic](https://github.com/qier222/YesPlayMusic) 官方仓库的主分支提交代码，未作任何代码修改，原汁原味，使用 `Github Actions` 自动编译，公开透明，自动编译镜像仓库地址：https://github.com/junlongzzz/YesPlayMusic

[![GitHub package.json version](https://img.shields.io/github/package-json/v/junlongzzz/YesPlayMusic)](https://github.com/junlongzzz/YesPlayMusic)

![Last Commit SHA](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fapi.github.com%2Frepos%2Fjunlongzzz%2Fyesplaymusic%2Fcommits%3Fper_page%3D1&query=%24%5B0%5D.sha&label=commit)

### Docker

```shell
docker run -d --name yesplaymusic -p 80:80 junlongzzz/yesplaymusic
```

### Docker Compose (推荐)

```yaml
services:
  yesplaymusic:
    image: junlongzzz/yesplaymusic
    container_name: yesplaymusic
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "80:80"
    restart: always
```
